# Tensor 연습 문제 초급

In [20]:
import torch

In [21]:
y=torch.tensor([2,3,4,5])

print(y.dim())

1


In [22]:
'''
[1번] 
아래 세 리스트 a, b, c를 이용해 이를 pytorch의 float64 type의 tensor로 바꾸고 그것의 크기를 print해 보세요
'''
a = [8, 6, 1]
b = [[1,7,4], [7,2,7]]
c = [[[1,2,3], [4,5,1],[9,8,2]], [[10,6,5], [2,2,7],[6,6,1]]]

# 아래에 풀이 적기 

In [23]:
#우선 리스트를 텐서로 바꿈.
d=torch.Tensor(a)
print(d.dtype)

#이 상태에선 자료형이 float32이기 때문에 to torch로 텐서의 자료형을 float64로 바꿈.
d = d.to(torch.float64)

print(d)
print(d.shape) #print(d.size())
print(d.dim())

torch.float32
tensor([8., 6., 1.], dtype=torch.float64)
torch.Size([3])
1


In [24]:
e=torch.Tensor(b)
e = e.to(torch.float64)

print(e)
print(e.size())
print(e.dim())

tensor([[1., 7., 4.],
        [7., 2., 7.]], dtype=torch.float64)
torch.Size([2, 3])
2


In [25]:
f=torch.Tensor(c)
f = f.to(torch.float64)

print(f)
print(f.size())
print(f.dim())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  1.],
         [ 9.,  8.,  2.]],

        [[10.,  6.,  5.],
         [ 2.,  2.,  7.],
         [ 6.,  6.,  1.]]], dtype=torch.float64)
torch.Size([2, 3, 3])
3


In [26]:
'''
[2번] 
아래 두 tensor a와 b의 합을 구하고 그 결과를 출력하세요 
'''

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 아래에 풀이 적기 


In [11]:
#텐서의 크기가 같기 때문에 바로 덧셈 가능.
if a.shape==b.shape:
  print(a.add(b))


tensor([5, 7, 9])


In [27]:
#간단하게 a+b로 해도 됨.
if a.shape==b.shape:
  print(a+b)
  

tensor([5, 7, 9])


In [4]:
'''
[3번] 
아래 tensor의 최솟값과 최댓값을 출력해세요 
'''
a = torch.tensor([2, 4, 1, 7, 5])

# 아래에 풀이 적기 


In [6]:
print(a.max())
#dim=0을 넣어주면 첫번째 차원을 제거함.
print('최대값',a.max(dim=0))
print('최소값',a.min(dim=0))

tensor(7)
최대값 torch.return_types.max(
values=tensor(7),
indices=tensor(3))
최소값 torch.return_types.min(
values=tensor(1),
indices=tensor(2))


In [9]:
'''
[4번] 
모든 값이 0으로 채워진 3 x 4 tensor a를 만드세요 
'''

# 아래에 풀이 적기 

tensor_a=torch.zeros(3,4)
print(tensor_a)

#torch.full은 원하는 값을 지정해 채울 수 있음.
tensor_a2=torch.full(size=(3,4), fill_value=0)
print(tensor_a2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [20]:
'''
[5번] 
3 이상 10 이하의 정수로 이루어진 3 x 4 크기의 tensor a를 만드세요 
'''

# 아래에 풀이 적기 
#randint(a,b,size=(c,d)) 로 랜덤값을 가지는 텐서 생성. a '이상' b '미만'의 범위로 생성됨.
tensor_a=torch.randint(3,11, size=(3,4))
print(tensor_a)

tensor([[ 3,  9, 10,  8],
        [ 6,  5,  6,  4],
        [ 9,  6,  7,  8]])


In [22]:
'''
[6번] 
아래 a tensor의 앞에서부터 2번 째 원소와 가장 마지막 원소를 출력하세요 
'''
a = torch.tensor([2, 4, 5, 7, 5])

# 아래에 풀이 적기 
print(a[1])
print(a[-1])

tensor(4)
tensor(5)


In [25]:
'''
[7번] 
아래 a tensor의 크기를 출력하고
이를 3 x 2 x 2 크기를 갖는 b tensor로 변경해보세요 
'''
a = torch.randn((2, 6))
print(a.shape)
b=a.reshape(3,2,2)
print(b)
print(b.shape)
# 아래에 풀이 적기 


torch.Size([2, 6])
tensor([[[-0.7829,  0.4146],
         [ 1.3554,  0.8902]],

        [[ 0.4299,  0.9516],
         [-1.5169, -0.2015]],

        [[ 1.4073, -1.1420],
         [-0.3799, -0.1693]]])
torch.Size([3, 2, 2])


In [28]:
'''
[8번] 
아래 a tensor의 모든 원소의 값을 3배 해 보세요 
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기 
print(a*3)


tensor([ 3,  6,  9, 12])


In [29]:
'''
[9번] 
아래 a tensor의 모든 원소의 값을 제곱 해 보세요 
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기 
print(a**2)


tensor([ 1,  4,  9, 16])


# Tensor 연습 문제 중급

In [18]:
'''
[1번] 
아래 a tensor를 첫 번째 차원을 기준으로 합을 구하세요 
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# 아래에 풀이 적기 

print(torch.sum(a,dim=0))

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [50]:
'''
[2번] 
아래 a tensor에서 5보다 작은 원소만 출력해보세요 
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기

#bool 은 boolean 연산을 수행해 a의 각 원소가 5보다 작은지 판단하는 1차원 bool 텐서를 만들어냄.
bool= a<5
print(bool)

#a[bool]을 하면 a텐서에서 bool텐서 값이 true인 위치에 있는 원소들만 선택해 새로운 텐서를 만들어 출력하게 됨.
#a[2]를 하면 9가 나오는 것과 같음. bool의 t/f값을 다 순회하면서 true인 인덱스만 출력함.
print(a[bool])

tensor([ True,  True, False,  True, False,  True, False,  True, False, False])
tensor([0, 1, 2, 3, 4])


In [55]:
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

#torch.where(n,True,False)로 위의 bool과 같은 결과를 도출할 수 있음. 
bool2=torch.where(a<5,True,False)
print(bool2)
print(a[bool2])

#index는 a<5를 만족하는 값이 있는 '인덱스'를 리스트로 반환함. 
#그래서 a[index]를 하면 a에서 해당 인덱스 위치의 값을 반환.
index=torch.where(a<5)
print(index)
print(a[index])


tensor([ True,  True, False,  True, False,  True, False,  True, False, False])
tensor([0, 1, 2, 3, 4])
(tensor([0, 1, 3, 5, 7]),)
tensor([0, 1, 2, 3, 4])


In [44]:
'''
[3번] 
아래 a tensor에서 짝수번째 원소만 출력해보세요 
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기 



In [50]:
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

#짝수 인덱스 담을 빈 리스트 만들기.
a_even = []

#a의 길이 만큼 순회
for i in range(len(a)):
    if i%2==1:
        #짝수 번째 원소들 출력
        print(a[i])
        #원소들 모으기 = 빈 리스트에 짝수 인덱스 a 원소를 삽입.
        # 그런데 리스트에 들어가는 것들이 하나의 숫자만 담고 있는 텐서 = 스칼라 = 0차원임.
        # 이 상태론 torch.cat으로 텐서들을 연결할 수 없음. 
        # 그래서 unsqueeze(0)으로 차원 하나를 추가함.
        a_even.append(a[i].unsqueeze(0))
        print(a_even)
#합쳐서 하나의 텐서로.
a_even_tensor=torch.cat(a_even)
print(a_even_tensor)
        
        

tensor(1)
[tensor([1])]
tensor(2)
[tensor([1]), tensor([2])]
tensor(3)
[tensor([1]), tensor([2]), tensor([3])]
tensor(4)
[tensor([1]), tensor([2]), tensor([3]), tensor([4])]
tensor(5)
[tensor([1]), tensor([2]), tensor([3]), tensor([4]), tensor([5])]
tensor([1, 2, 3, 4, 5])


In [47]:
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])
a_even = []

#간결하게 2번째 텐서부터 시작해 한 칸씩 건너뛰며 반복
for i in range(1,len(a),2):
    print(a[i])
    a_even.append(a[i].unsqueeze(0))
a_even_tensor=torch.cat(a_even)
print(a_even_tensor)
        
        

tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor([1, 2, 3, 4, 5])


In [52]:
'''
[4번] 
아래 a tensor의 원소를 반대의 순서로 갖는 tensor b를 만드세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기 


In [61]:
#flip함수 = 텐서를 지정한 차원을 기준으로 뒤집는다.
b_tensor= torch.flip(a, dims=[0])
print(b_tensor)

tensor([5, 6, 4, 7, 3, 8, 2, 9, 1, 0])


In [53]:
b= []

#a를 거꾸로 순회
for i in reversed(range(len(a))):
    print(a[i])
    b.append(a[i].unsqueeze(0))
b_tensor=torch.cat(b)
print(b_tensor)

tensor(5)
tensor(6)
tensor(4)
tensor(7)
tensor(3)
tensor(8)
tensor(2)
tensor(9)
tensor(1)
tensor(0)
tensor([5, 6, 4, 7, 3, 8, 2, 9, 1, 0])


In [59]:
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

b= []
#range 함수의 인자 - 시작, 끝, 스탭을 이용. 
#len(a)는 10이므로 9부터 시작시키기 위해서, 끝 숫자에서 1앞에서 끝나기 때문에 시작과 끝에 -1을 해줌.
#step을 -1로 하면 거꾸로 순회함.
for i in range(len(a)-1,-1,-1):
    b.append(a[i].unsqueeze(0))
b_tensor=torch.cat(b)
print(b_tensor)

tensor([5, 6, 4, 7, 3, 8, 2, 9, 1, 0])


In [ ]:
'''
[5번] 
아래 a tensor를 모든 차원에대해 최소값과 최대값을 구하세요. 
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

# 아래에 풀이 적기 

#차원 크기만큼 순회
for i in range(a.dim()):
  #a.max와 min으로 최대최소값 구함.
  print(a.max(dim=i).values)
  print(a.min(dim=i).values)

In [64]:
'''
[6번] 
아래 a tensor의 짝수 행은 모두 0으로 홀수 행은 모두 1로 바꾸세요
'''
import torch
a = torch.tensor(
    [
        [0, 0, 0], # 1번째 행 
        [1, 1, 1], # 2번째 행 
        [2, 2, 2], # 3번째 행 
        [3, 3, 3], # 4번째 행 
        [4, 4, 4], # 5번째 행 
        [5, 5, 5], # 6번째 행 
        [6, 6, 6], # 7번째 행 
        [7, 7, 7], # 8번째 행 
        [8, 8, 8], # 9번째 행 
        [9, 9, 9], # 10번째 행 
    ]
)

# 아래에 풀이 적기 
#a의 첫 번째 차원을 순회. 0or 1에서 시작해 끝까지 가면서 한 단계씩 건너뜀. 
#그리고 값을 1와 0으로 바꿈. 
a[::2] = 1  # 홀수 행 1
a[1::2] = 0 # 짝수 행 0

print(a)


tensor([[1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]])


In [63]:
#scatter를 쓰는 방법

a = torch.tensor(
    [
        [0, 0, 0], # 1번째 행 
        [1, 1, 1], # 2번째 행 
        [2, 2, 2], # 3번째 행 
        [3, 3, 3], # 4번째 행 
        [4, 4, 4], # 5번째 행 
        [5, 5, 5], # 6번째 행 
        [6, 6, 6], # 7번째 행 
        [7, 7, 7], # 8번째 행 
        [8, 8, 8], # 9번째 행 
        [9, 9, 9], # 10번째 행 
    ]
)

# a를 0텐서로 초기화시킴.
a = torch.zeros_like(a)

# 인덱스를 지정할 텐서 만들기 
#1.a의 1차원의 크기(10)까지의 홀수만 가지는 텐서 생성
odd_tensor=torch.tensor(range(0,a.size(0),2))

#2.a와 차원을 맞추기 위해 이 텐서에 차원 하나를 더 추가.
odd_tensor2=odd_tensor.unsqueeze(1)

#3.a의 2번째 차원의 텐서 크기(3)만큼 확장시켜줌. 
odd_tensor3=odd_tensor2.expand(-1, a.size(1))

# 짝수 행은 0으로 놔두고 홀수 행은 1로 채우기
# scatter의 첫 번째 인자=값 채울 텐서의 축 
# 두 번째 인자 = 값 채울 인덱스. 이걸 odd_tensor3로 지정. 
# 세 번째 인자 = 채울 값 = 1

a.scatter_(0, odd_tensor3, 1)

print(a)

tensor([[1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]])


In [83]:
'''
[7번] 
아래 a tensor의 짝수 열은 모두 0으로 홀수 열은 모두 1로 바꾸세요
'''
import torch
a = torch.tensor(
    [
        [0,    0,    0], 
        [1,    1,    1], 
        [2,    2,    2], 
        [3,    3,    3], 
        [4,    4,    4], 
        [5,    5,    5], 
        [6,    6,    6], 
        [7,    7,    7], 
        [8,    8,    8], 
        [9,    9,    9], 
    ] # 1열  2열    3열
)
# 아래에 풀이 적기 
for row in 
print(a.size()[1])


3


In [ ]:
a = torch.tensor(
    [
        [0,    0,    0], 
        [1,    1,    1], 
        [2,    2,    2], 
        [3,    3,    3], 
        [4,    4,    4], 
        [5,    5,    5], 
        [6,    6,    6], 
        [7,    7,    7], 
        [8,    8,    8], 
        [9,    9,    9], 
    ] # 1열  2열    3열
)

for column in range(a.size()[0]):
  for row in range(a.size()[1]):
    if row%2==1:
      a[column][row]=0
    else:
      a[column][row]=1

print(a)

In [ ]:
a = torch.tensor(
    [
        [0,    0,    0], 
        [1,    1,    1], 
        [2,    2,    2], 
        [3,    3,    3], 
        [4,    4,    4], 
        [5,    5,    5], 
        [6,    6,    6], 
        [7,    7,    7], 
        [8,    8,    8], 
        [9,    9,    9], 
    ] # 1열  2열    3열
)

a[:,::2]=1
for row in range(a.size()[1]):
  if row%2==1:
    a[:, row::2] = 0

print(a)



a[:, ::2] = 0은 모든 행(:)에서 0번째, 2번째, 4번째, ... 인덱스(column)의 원소들을 0으로 바꾸는 작업을 수행합니다. 콜론(:)의 의미는 해당 차원 전체를 의미하는 것이며, ::2에서 콜론 뒤의 ::2는 간격(step)을 의미합니다. 즉, 2의 간격으로 인덱스(column)를 선택하여 값을 바꾸는 것입니다.
a[:, 1::2] = 1은 모든 행(:)에서 1번째, 3번째, 5번째, ... 인덱스(column)의 원소들을 1로 바꾸는 작업을 수행합니다. 이 또한 간격(step)이 2이기 때문에, 1::2로 인덱스(column)를 선택하여 값을 바꾸는 것입니다.
결과적으로, 이 코드는 numpy array 'a'의 짝수 인덱스(column)는 0, 홀수 인덱스(column)는 1로 만드는 작업을 수행합니다.

In [ ]:
'''
[8번] 
아래 a tensor를 오름차순과 내림차순으로 정렬해보세요 
 
'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기 


# Tensor 연습 문제 고급

In [ ]:
'''
[1번] 
아래 a tensor에서 0.3 보다 큰 값의 수를 출력해 보세요
'''
a = torch.randn((2,5,3))

# 아래에 풀이 적기 


In [ ]:
'''
[2번] 
아래 a tensor에서 음수는 모두 0으로 바꾸세요
'''
a = torch.tensor(
    [
        [-2, -1,  2,  5],
        [ 1,  1, -1,  0],
        [ 2, -1, -1, -1],
        [-1, -1, -1,  3],
        [ 0, -1,  1,  2],
        [ 1, -1,  1, -1],
    ]
)

# 아래에 풀이 적기 


In [ ]:
#사람들이 지나가면서 쳐다보는 걱 ㅏㅌ아 민망해서 ㅋㅋㅋ

In [ ]:
'''
[3번] 
아래 a tensor를 sigmoid 함수를 적용시켜보세요 
sigmoid 함수 : 1 / (1 + e^(-x))
그리고 torch.sigmoid(a)의 결과와 비교해 보세요 
'''
a = torch.tensor([1, 3, 5])

# 아래에 풀이 적기 


In [ ]:
'''
[4번] 
아래 a tensor를 평균이 0 표준편차가 1이 되도록 정규화 코드를 작성하세요 
'''
a = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

# 아래에 풀이 적기 


In [ ]:
'''
[5번] 
아래 a tensor의 모든 원소를 오름차순으로 정렬한 후 크기 기준 상위 10%의 원소만 출력해보세요
'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기 


In [ ]:
'''
[6번] 
아래 a tensor를 1차원으로 평탄화하고, 각 원소가 몇 번 등장하는지 세어 결과를 딕셔너리로 출력하는 코드를 작성하시오
'''
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 아래에 풀이 적기 


In [ ]:
'''
[7번] 
인덱싱과 슬라이싱을 활용해 아래 a tensor에서 [[4, 5], [7, 8]]를 출력해 보세요
'''
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 아래에 풀이 적기 
