# Tensor 연습 문제 초급

In [1]:
import torch

In [3]:
'''
[1번] 
아래 세 리스트 a, b, c를 이용해 이를 pytorch의 float64 type의 tensor로 바꾸고 그것의 크기를 print해 보세요
'''
a = [8, 6, 1]
b = [[1,7,4], [7,2,7]]
c = [[[1,2,3], [4,5,1],[9,8,2]], [[10,6,5], [2,2,7],[6,6,1]]]

# 아래에 풀이 적기 

In [20]:
#우선 리스트를 텐서로 바꿈.
d=torch.Tensor(a)
print(d.dtype)

#이 상태에선 자료형이 float32이기 때문에 to torch로 텐서의 자료형을 float64로 바꿈.
d = d.to(torch.float64)

print(d)
print(d.shape) #print(d.size())
print(d.dim())

torch.float32
tensor([8., 6., 1.], dtype=torch.float64)
torch.Size([3])
torch.Size([3])
1


In [15]:
e=torch.Tensor(b)
e = e.to(torch.float64)

print(e)
print(e.size())
print(e.dim())

tensor([[1., 7., 4.],
        [7., 2., 7.]], dtype=torch.float64)
torch.Size([2, 3])
2


In [14]:
f=torch.Tensor(c)
f = f.to(torch.float64)

print(f)
print(f.size())
print(f.dim())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  1.],
         [ 9.,  8.,  2.]],

        [[10.,  6.,  5.],
         [ 2.,  2.,  7.],
         [ 6.,  6.,  1.]]], dtype=torch.float64)
torch.Size([2, 3, 3])
3


In [21]:
'''
[2번] 
아래 두 tensor a와 b의 합을 구하고 그 결과를 출력하세요 
'''

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 아래에 풀이 적기 


In [23]:
#텐서의 크기가 같기 때문에 바로 덧셈 가능.
if a.shape==b.shape:
  print(a+b)

tensor([5, 7, 9])


In [24]:
'''
[3번] 
아래 tensor의 최솟값과 최댓값을 출력해세요 
'''
a = torch.tensor([2, 4, 1, 7, 5])

# 아래에 풀이 적기 


In [26]:
print(a.max())
#dim=0을 넣어주면 ㅊ
print(a.max(dim=0))

torch.return_types.max(
values=tensor(7),
indices=tensor(3))

In [ ]:
'''
[4번] 
모든 값이 0으로 채워진 3 x 4 tensor a를 만드세요 
'''

# 아래에 풀이 적기 


In [ ]:
'''
[5번] 
3 이상 10 이하의 정수로 이루어진 3 x 4 크기의 tensor a를 만드세요 
'''

# 아래에 풀이 적기 


In [ ]:
'''
[6번] 
아래 a tensor의 앞에서부터 2번 째 원소와 가장 마지막 원소를 출력하세요 
'''
a = torch.tensor([2, 4, 5, 7, 5])

# 아래에 풀이 적기 


In [ ]:
'''
[7번] 
아래 a tensor의 크기를 출력하고
이를 3 x 2 x 2 크기를 갖는 b tensor로 변경해보세요 
'''
a = torch.randn((2, 6))

# 아래에 풀이 적기 


In [ ]:
'''
[8번] 
아래 a tensor의 모든 원소의 값을 3배 해 보세요 
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기 


In [ ]:
'''
[9번] 
아래 a tensor의 모든 원소의 값을 제곱 해 보세요 
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기 


# Tensor 연습 문제 중급

In [ ]:
'''
[1번] 
아래 a tensor를 첫 번째 차원을 기준으로 합을 구하세요 
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# 아래에 풀이 적기 


In [ ]:
'''
[2번] 
아래 a tensor에서 5보다 작은 원소만 출력해보세요 
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기 


In [ ]:
'''
[3번] 
아래 a tensor에서 짝수번째 원소만 출력해보세요 
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기 


In [ ]:
'''
[4번] 
아래 a tensor의 원소를 반대의 순서로 갖는 tensor b를 만드세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기 


In [ ]:
'''
[5번] 
아래 a tensor를 모든 차원에대해 최소값과 최대값을 구하세요. 
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

# 아래에 풀이 적기 


In [ ]:
'''
[6번] 
아래 a tensor의 짝수 행은 모두 0으로 홀수 행은 모두 1로 바꾸세요
'''
a = torch.tensor(
    [
        [0, 0, 0], # 1번째 행 
        [1, 1, 1], # 2번째 행 
        [2, 2, 2], # 3번째 행 
        [3, 3, 3], # 4번째 행 
        [4, 4, 4], # 5번째 행 
        [5, 5, 5], # 6번째 행 
        [6, 6, 6], # 7번째 행 
        [7, 7, 7], # 8번째 행 
        [8, 8, 8], # 9번째 행 
        [9, 9, 9], # 10번째 행 
    ]
)

# 아래에 풀이 적기 


In [ ]:
'''
[7번] 
아래 a tensor의 짝수 열은 모두 0으로 홀수 열은 모두 1로 바꾸세요
'''
a = torch.tensor(
    [
        [0,    0,    0], 
        [1,    1,    1], 
        [2,    2,    2], 
        [3,    3,    3], 
        [4,    4,    4], 
        [5,    5,    5], 
        [6,    6,    6], 
        [7,    7,    7], 
        [8,    8,    8], 
        [9,    9,    9], 
    ] # 1열  2열    3열
)

# 아래에 풀이 적기 


In [ ]:
'''
[8번] 
아래 a tensor를 오름차순과 내림차순으로 정렬해보세요 
 
'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기 


# Tensor 연습 문제 고급

In [ ]:
'''
[1번] 
아래 a tensor에서 0.3 보다 큰 값의 수를 출력해 보세요
'''
a = torch.randn((2,5,3))

# 아래에 풀이 적기 


In [ ]:
'''
[2번] 
아래 a tensor에서 음수는 모두 0으로 바꾸세요
'''
a = torch.tensor(
    [
        [-2, -1,  2,  5],
        [ 1,  1, -1,  0],
        [ 2, -1, -1, -1],
        [-1, -1, -1,  3],
        [ 0, -1,  1,  2],
        [ 1, -1,  1, -1],
    ]
)

# 아래에 풀이 적기 


In [ ]:
'''
[3번] 
아래 a tensor를 sigmoid 함수를 적용시켜보세요 
sigmoid 함수 : 1 / (1 + e^(-x))
그리고 torch.sigmoid(a)의 결과와 비교해 보세요 
'''
a = torch.tensor([1, 3, 5])

# 아래에 풀이 적기 


In [ ]:
'''
[4번] 
아래 a tensor를 평균이 0 표준편차가 1이 되도록 정규화 코드를 작성하세요 
'''
a = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

# 아래에 풀이 적기 


In [ ]:
'''
[5번] 
아래 a tensor의 모든 원소를 오름차순으로 정렬한 후 크기 기준 상위 10%의 원소만 출력해보세요
'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기 


In [ ]:
'''
[6번] 
아래 a tensor를 1차원으로 평탄화하고, 각 원소가 몇 번 등장하는지 세어 결과를 딕셔너리로 출력하는 코드를 작성하시오
'''
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 아래에 풀이 적기 


In [ ]:
'''
[7번] 
인덱싱과 슬라이싱을 활용해 아래 a tensor에서 [[4, 5], [7, 8]]를 출력해 보세요
'''
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 아래에 풀이 적기 
