# Tensor 연습 문제 초급

In [ ]:
import torch

In [ ]:
'''
[1번] 
아래 세 리스트 a, b, c를 이용해 이를 pytorch의 float64 type의 tensor로 바꾸고 그것의 크기를 print해 보세요
'''
a = [8, 6, 1]
b = [[1,7,4], [7,2,7]]
c = [[[1,2,3], [4,5,1],[9,8,2]], [[10,6,5], [2,2,7],[6,6,1]]]

# 아래에 풀이 적기 

#우선 리스트를 텐서로 바꿈.
d=torch.Tensor(a)

#이 상태에선 자료형이 float32이기 때문에 to torch로 텐서의 자료형을 float64로 바꿈.
d = d.to(torch.float64)

print(d.shape) #print(d.size())


torch.Size([3])


In [ ]:
'''
[2번] 
아래 두 tensor a와 b의 합을 구하고 그 결과를 출력하세요 
'''

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 아래에 풀이 적기 

#텐서의 크기가 같기 때문에 바로 덧셈 가능.
if a.shape==b.shape:
  print(a.add(b))

  #간단하게 a+b로 해도 됨.
if a.shape==b.shape:
  print(a+b)
  


tensor([5, 7, 9])
tensor([5, 7, 9])


In [ ]:
'''
[3번] 
아래 tensor의 최솟값과 최댓값을 출력해세요 
'''
a = torch.tensor([2, 4, 1, 7, 5])

# 아래에 풀이 적기 
print(a.max())
#dim=0을 넣어주면 첫번째 차원을 제거함.
print('최대값',a.max(dim=0).values)
print('최소값',a.min(dim=0).values)

tensor(7)
최대값 tensor(7)
최소값 tensor(1)


In [ ]:
'''
[4번] 
모든 값이 0으로 채워진 3 x 4 tensor a를 만드세요 
'''

# 아래에 풀이 적기 

tensor_a=torch.zeros(3,4)
print(tensor_a)

#torch.full은 원하는 값을 지정해 채울 수 있음.
tensor_a2=torch.full(size=(3,4), fill_value=0)
print(tensor_a2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [ ]:
'''
[5번] 
3 이상 10 이하의 정수로 이루어진 3 x 4 크기의 tensor a를 만드세요 
'''

# 아래에 풀이 적기 
#randint(a,b,size=(c,d)) 로 랜덤값을 가지는 텐서 생성. a '이상' b '미만'의 범위로 생성됨.
tensor_a=torch.randint(3,11, size=(3,4))
print(tensor_a)

tensor([[7, 8, 6, 9],
        [7, 3, 3, 8],
        [9, 4, 8, 9]])


In [ ]:
'''
[6번] 
아래 a tensor의 앞에서부터 2번 째 원소와 가장 마지막 원소를 출력하세요 
'''
a = torch.tensor([2, 4, 5, 7, 5])

# 아래에 풀이 적기 

#인덱싱.맨 앞은 [0]이고 맨 끝은 [-1]
print(a[1])
print(a[-1])

tensor(4)
tensor(5)


In [ ]:
'''
[7번] 
아래 a tensor의 크기를 출력하고
이를 3 x 2 x 2 크기를 갖는 b tensor로 변경해보세요 
'''
a = torch.randn((2, 6))

# 아래에 풀이 적기 
print(a.size())
b=a.reshape(3,2,2)
print(b.size())

torch.Size([2, 6])
torch.Size([3, 2, 2])


In [ ]:
'''
[8번] 
아래 a tensor의 모든 원소의 값을 3배 해 보세요 
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기 
print(a*3)


tensor([ 3,  6,  9, 12])


In [ ]:
'''
[9번] 
아래 a tensor의 모든 원소의 값을 제곱 해 보세요 
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기 
print(a**2)


tensor([ 1,  4,  9, 16])


# Tensor 연습 문제 중급

In [ ]:
'''
[1번] 
아래 a tensor를 첫 번째 차원을 기준으로 합을 구하세요 
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# 아래에 풀이 적기 

#첫 번째 차원인 [1,2,3]끼리, [4,5,6]끼리 더해줌.
print(torch.sum(a,dim=0))

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [ ]:
'''
[2번] 
아래 a tensor에서 5보다 작은 원소만 출력해보세요 
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기

#방법1

#bool 은 boolean 연산을 수행해 a의 각 원소가 5보다 작은지 판단하는 1차원 bool 텐서를 만들어냄.
bool= a<5
print(bool)

#a[bool]을 하면 슬라이싱 연산으로 a텐서에서 bool텐서 값이 true인 위치에 있는 원소들만 선택해 새로운 텐서를 만들어 출력하게 됨.
#a[2]를 하면 9가 나오는 것과 같음. bool의 t/f값을 다 순회하면서 true인 인덱스만 출력함.
print(a[bool])

tensor([ True,  True, False,  True, False,  True, False,  True, False, False])
tensor([0, 1, 2, 3, 4])


In [ ]:

#[2번] 방법 2

#torch.where(n,True,False)로 위의 bool과 같은 결과를 도출할 수 있음. 
bool2=torch.where(a<5,True,False)
print(bool2)
print(a[bool2])



tensor([ True,  True, False,  True, False,  True, False,  True, False, False])
tensor([0, 1, 2, 3, 4])


In [ ]:
#[2번] 방법 3

#index는 a<5를 만족하는 값이 있는 '인덱스'를 리스트로 반환함. 
#그래서 a[index]를 하면 a에서 해당 인덱스 위치의 값을 반환.
index=torch.where(a<5)
print(index)
print(a[index])

(tensor([0, 1, 3, 5, 7]),)
tensor([0, 1, 2, 3, 4])


In [ ]:
'''
[3번] 
아래 a tensor에서 짝수번째 원소만 출력해보세요 
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기 

#[3번] 방법 1

#짝수 인덱스 담을 빈 리스트 만들기.
a_even = []

#a의 길이 만큼 순회
for i in range(len(a)):
    #짝수 번째 원소들 일 경우
    if i%2==1:
        # 원소들 모으기 = 빈 리스트에 짝수 인덱스 a 원소를 삽입.

        # 그런데 리스트에 들어가는 것들이 하나의 숫자만 담고 있는 텐서 = 스칼라 = 0차원임.
        #   이 상태론 torch.cat으로 텐서들을 연결할 수 없음. 
        #   그래서 unsqueeze(0)으로 차원 하나를 추가함.
        a_even.append(a[i].unsqueeze(0))

print(a_even)

#합쳐서 하나의 텐서로.
a_even_tensor=torch.cat(a_even)
print(a_even_tensor)

[tensor([1]), tensor([2]), tensor([3]), tensor([4]), tensor([5])]
tensor([1, 2, 3, 4, 5])


In [ ]:
#[3번] 방법 2

a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])
a_even2 = []

#반복문 간결하게 만듦. 2번째 텐서부터 시작해 한 칸씩 건너뛰며 반복.
for i in range(1,len(a),2):
    a_even2.append(a[i].unsqueeze(0))

a_even2_tensor=torch.cat(a_even2)
print(a_even2_tensor)
        
        

tensor([1, 2, 3, 4, 5])


In [ ]:
'''
[4번] 
아래 a tensor의 원소를 반대의 순서로 갖는 tensor b를 만드세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기 

#[4번] 방법 1

#flip함수 = 텐서를 지정한 차원을 기준으로 뒤집는다.
b_tensor= torch.flip(a, dims=[0])
print(b_tensor)


tensor([5, 6, 4, 7, 3, 8, 2, 9, 1, 0])


In [ ]:
#[4번] 방법 2

b_list= []

#a를 거꾸로 순회, 리스트에 삽입.
for i in reversed(range(len(a))):
    b_list.append(a[i].unsqueeze(0))

#리스트를 텐서로.
b_tensor=torch.cat(b_list)
print(b_tensor)

tensor([5, 6, 4, 7, 3, 8, 2, 9, 1, 0])


In [ ]:
#[4번] 방법 3

b_list2= []
#range 함수의 인자 - 시작, 끝, 스탭을 이용. 
#len(a)는 10이므로 9부터 시작시키기 위해서, 끝 숫자에서 1앞에서 끝나기 때문에 시작과 끝에 -1을 해줌.
#step을 -1로 하면 거꾸로 순회함.
for i in range(len(a)-1,-1,-1):
    b_list2.append(a[i].unsqueeze(0))
b_tensor2=torch.cat(b_list2)
print(b_tensor2)

tensor([5, 6, 4, 7, 3, 8, 2, 9, 1, 0])


In [ ]:
'''
[5번] 
아래 a tensor를 모든 차원에대해 최소값과 최대값을 구하세요. 
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

# 아래에 풀이 적기 

#차원 크기만큼 순회
for i in range(a.dim()):
  #a.max와 min으로 최대최소값 구함.
  print(f'{i+1}번째 차원의 최대값은',a.max(dim=i).values)
  print(f'{i+1}번째 차원의 최소값은',a.min(dim=i).values)

1번째 차원의 최대값은 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
1번째 차원의 최소값은 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2번째 차원의 최대값은 tensor([[7, 8, 9]])
2번째 차원의 최소값은 tensor([[1, 2, 3]])
3번째 차원의 최대값은 tensor([[3, 6, 9]])
3번째 차원의 최소값은 tensor([[1, 4, 7]])


In [ ]:
'''
[6번] 
아래 a tensor의 짝수 행은 모두 0으로 홀수 행은 모두 1로 바꾸세요
'''
import torch
a = torch.tensor(
    [
        [0, 0, 0], # 1번째 행 
        [1, 1, 1], # 2번째 행 
        [2, 2, 2], # 3번째 행 
        [3, 3, 3], # 4번째 행 
        [4, 4, 4], # 5번째 행 
        [5, 5, 5], # 6번째 행 
        [6, 6, 6], # 7번째 행 
        [7, 7, 7], # 8번째 행 
        [8, 8, 8], # 9번째 행 
        [9, 9, 9], # 10번째 행 
    ]
)

# 아래에 풀이 적기 

#[6번] 방법 1

#a의 첫 번째 차원을 순회. 0or 1에서 시작해 끝까지 가면서 한 단계씩 건너뜀. 
#그리고 값을 1와 0으로 바꿈. 
a[::2] = 1  # 홀수 행 1
a[1::2] = 0 # 짝수 행 0

print(a)


tensor([[1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]])


In [ ]:
#[6번] 방법 2

#scatter를 쓰는 방법

# a를 0텐서로 초기화시킴.
a = torch.zeros_like(a)

# 인덱스를 지정할 텐서 만들기 
#1.a의 1차원의 크기(10)까지의 홀수만 가지는 텐서 생성
odd_tensor=torch.tensor(range(0,a.size(0),2))

#2.a와 차원을 맞추기 위해 이 텐서에 차원 하나를 더 추가.
odd_tensor2=odd_tensor.unsqueeze(1)

#3.a의 2번째 차원의 텐서 크기(3)만큼 확장시켜줌. 
odd_tensor3=odd_tensor2.expand(-1, a.size(1))

# 짝수 행은 0으로 놔두고 홀수 행은 1로 채우기
# scatter의 첫 번째 인자=값 채울 텐서의 축 
# 두 번째 인자 = 값 채울 인덱스. 이걸 odd_tensor3로 지정. 
# 세 번째 인자 = 채울 값 = 1

a.scatter_(0, odd_tensor3, 1)

print(a)

tensor([[1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]])


In [ ]:
'''
[7번] 
아래 a tensor의 짝수 열은 모두 0으로 홀수 열은 모두 1로 바꾸세요
'''
import torch
a = torch.tensor(
    [
        [0,    0,    0], 
        [1,    1,    1], 
        [2,    2,    2], 
        [3,    3,    3], 
        [4,    4,    4], 
        [5,    5,    5], 
        [6,    6,    6], 
        [7,    7,    7], 
        [8,    8,    8], 
        [9,    9,    9], 
    ] # 1열  2열    3열
)
# 아래에 풀이 적기 

#[7번] 방법 1

#행과 열의 인덱스값(?)을 각각 a.size()[0]과 [1]을 이용해 추출하고 순회함.
for column in range(a.size()[1]):
  for row in range(a.size()[0]):
    #짝수열이면 0으로. 
    if column%2==1:
      a[row][column]=0
    else:
      a[row][column]=1

print(a)

tensor([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]])


In [ ]:
#[7번] 방법 2



a = torch.tensor(
    [
        [0,    0,    0], 
        [1,    1,    1], 
        [2,    2,    2], 
        [3,    3,    3], 
        [4,    4,    4], 
        [5,    5,    5], 
        [6,    6,    6], 
        [7,    7,    7], 
        [8,    8,    8], 
        [9,    9,    9], 
    ] # 1열  2열    3열
)


#모든 행을 순회하면서(=":,") 0부터 시작해 끝까지 가면서(::) 두 칸씩 건너가며 값을 1로 바꿈.
a[:,::2]=1
#마찬가지이나 1부터 시작함.
a[:,1::2]=0
print(a)


tensor([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]])


In [ ]:
'''
[8번] 
아래 a tensor를 오름차순과 내림차순으로 정렬해보세요 
 
'''
import torch
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기 


In [ ]:
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])
print(a.sort(descending=False).values)
print(a.sort(descending=True).values)

<class 'torch.Tensor'>
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


# Tensor 연습 문제 고급

In [ ]:
'''
[1번] 
아래 a tensor에서 0.3 보다 큰 값의 수를 출력해 보세요
'''
a = torch.randn((2,5,3))

# 아래에 풀이 적기

# [a>0.3]은 조건의 true/false를 가지는 리스트가 나옴. 이걸 이용해 슬라이싱하여 1차원 배열로 반환.

print(a[a>0.3])

tensor([2.3021, 1.3478, 1.1939, 0.4408, 0.4788, 1.4642, 0.4448, 0.9560, 1.5142,
        0.6892])


In [ ]:
'''
[2번] 
아래 a tensor에서 음수는 모두 0으로 바꾸세요
'''
a = torch.tensor([[-2, -1,  2,  5],[ 1,  1, -1,  0],[ 2, -1, -1, -1],[-1, -1, -1,  3],[ 0, -1,  1,  2],[ 1, -1,  1, -1],])

# 아래에 풀이 적기 


In [ ]:
#[2번] 방법 1

#첫 번째 차원을 순회
for i in a:
  #두 번째 차원의 값을 첫 번째 차원 길이를 이용해 인덱싱하고 순회
  for r in range(len(a[0])):
    #값이 0보다 작으면 0으로.
    if i[r]<0:
            i[r]=0
print(a)

tensor([[0, 0, 2, 5],
        [1, 1, 0, 0],
        [2, 0, 0, 0],
        [0, 0, 0, 3],
        [0, 0, 1, 2],
        [1, 0, 1, 0]])


In [ ]:
#[2번] 방법 2 torch.clamp 사용.

a = torch.tensor([[-2, -1,  2,  5],[ 1,  1, -1,  0],[ 2, -1, -1, -1],[-1, -1, -1,  3],[ 0, -1,  1,  2],[ 1, -1,  1, -1],])

#clamp는 텐서 요소들을 주어진 최소값과 최대값 사이의 값으로 잘라냄. 최소값을 0으로 함. 
a = torch.clamp(a, min=0)
print(a)

tensor([[0, 0, 2, 5],
        [1, 1, 0, 0],
        [2, 0, 0, 0],
        [0, 0, 0, 3],
        [0, 0, 1, 2],
        [1, 0, 1, 0]])


In [ ]:
'''
[3번] 
아래 a tensor를 sigmoid 함수를 적용시켜보세요 
sigmoid 함수 : 1 / (1 + e^(-x))
그리고 torch.sigmoid(a)의 결과와 비교해 보세요 
'''
a = torch.tensor([1, 3, 5])

# 아래에 풀이 적기 

#자연상수 e 불러오기 위해 math 사용.
import math

def sigmoid(x):
    y=1 / (1 + math.exp(-x))
    return y 

#빈 리스트 만들고 a의 원소에 각각 sigmoid 함수 적용한 걸 넣음. 그리고 tensor로 바꿔줌.
b=[]
for i in a:
    b.append(sigmoid(i))
    print(sigmoid(i))
print(torch.tensor(b))
print(torch.sigmoid(a))

#텐서로 바꾸기 전에는 소수점 5번째 자리 이후도 나왔는데 텐서로 하면 사라짐.

0.7310585786300049
0.9525741268224334
0.9933071490757153
tensor([0.7311, 0.9526, 0.9933])
tensor([0.7311, 0.9526, 0.9933])


In [ ]:
'''
[4번] 
아래 a tensor를 평균이 0 표준편차가 1이 되도록 정규화 코드를 작성하세요 
'''
a = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
print(torch.mean(a))
print(torch.std(a))
# 아래에 풀이 적기 

#각 원소에서 평균을 뺀 후 표준편차로 나눔.

def Normalization(x):
    for i in range(len(x)):
        x[i]= (x[i]- torch.mean(a))/torch.std(a)
    return x
print(Normalization(a))
print(torch.mean(Normalization(a)))
print(torch.std(Normalization(a)))


tensor(3.)
tensor(1.5811)
tensor([-1.2649, -0.2273,  0.3304,  0.8812,  1.6885])
tensor(0.0529)
tensor(1.0127)


In [ ]:
'''
[5번] 
아래 a tensor의 모든 원소를 오름차순으로 정렬한 후 크기 기준 상위 10%의 원소만 출력해보세요
'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기 

#상위 10%의 기준 숫자를 잡음. 뒤에서부터 슬라이스할 거기 때문에 음수 및 정수로 바꿔줌.
top10per_num=int(-len(a)/10)

#a를 정렬함
a_sorted=torch.sort(a).values

#위에서 뽑은 상위 10% 기준점으로 슬라이싱.
print(a_sorted[top10per_num:])



tensor([9])


In [ ]:
'''
[6번] 
아래 a tensor를 1차원으로 평탄화하고, 각 원소가 몇 번 등장하는지 세어 결과를 딕셔너리로 출력하는 코드를 작성하시오
'''
a = torch.tensor([[1, 2, 2], [3, 3, 3], [4, 4, 4],[4,5,5],[5,5,5]])

# 아래에 풀이 적기 


#torch.ravel = 텐서를 1차원 벡터로 평탄화. 리스트로 만듦.
flat_a=list(torch.ravel(a))

# 숫자 중복이 제거된 값들이 들어갈 리스트
no_duplication = [] 
for value in flat_a:
    if value not in no_duplication:
        no_duplication.append(value)

#각 값들의 개수가 담긴 리스트
count_list=[]

#평탄화한 리스트에서 값을 세고 그 값을 count_list에 넣음.
for i in flat_a:
  if flat_a.count(i) not in count_list:
   count_list.append(flat_a.count(i))

#최종적으로 원소와 그 개수 두 리스트를 이용해 딕셔러니 만듦.
final_dict=dict(zip(no_duplication,count_list))
print(final_dict)

{tensor(1): 1, tensor(2): 2, tensor(3): 3, tensor(4): 4, tensor(5): 5}


In [ ]:
'''
[7번] 
인덱싱과 슬라이싱을 활용해 아래 a tensor에서 [[4, 5], [7, 8]]를 출력해 보세요
'''
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 아래에 풀이 적기 

#1행부터 시작하고("1:",)1행의 첫 번째 원소부터 시작하며('0')두 번째 원소까지(:2) 슬라이싱.
result = a[1:,0:2]
print(result)

tensor([[4, 5],
        [7, 8]])
